### ISSUE TITLE
Could not resolve com.ironsource.sdk:mediationsdk:8.2.1.

### ISSUE THREAD

**Issue by julienpierron** [cleveradssolutions/CAS-Android#7]
I am trying to implement CAS using Option 2 (No plugin integration).

It fails to resolve 2 libraries :
`> Could not resolve com.ironsource.sdk:mediationsdk:8.2.1.`
`> Could not resolve com.chartboost:chartboost-sdk:9.7.0.`

log :

```
> Task :my_app:writeDevDebugSigningConfigVersions UP-TO-DATE

FAILURE: Build completed with 7 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':my_app:checkDevDebugAarMetadata'.
> Could not resolve all files for configuration ':my_app:devDebugRuntimeClasspath'.
   > Could not resolve com.ironsource.sdk:mediationsdk:8.2.1.
     Required by:
         project :my_app > com.cleveradssolutions:cas-families:3.9.3 > com.cleveradssolutions:ironsource:8.2.1.2
      > No cached version of com.ironsource.sdk:mediationsdk:8.2.1 available for offline mode.
      > No cached version of com.ironsource.sdk:mediationsdk:8.2.1 available for offline mode.
      > No cached version of com.ironsource.sdk:mediationsdk:8.2.1 available for offline mode.
      > No cached version of com.ironsource.sdk:mediationsdk:8.2.1 available for offline mode.
      > No cached version of com.ironsource.sdk:mediationsdk:8.2.1 available for offline mode.
      > No cached version of com.ironsource.sdk:mediationsdk:8.2.1 available for offline mode.
   > Could not resolve com.chartboost:chartboost-sdk:9.7.0.
     Required by:
         project :my_app > com.cleveradssolutions:cas-families:3.9.3 > com.cleveradssolutions:chartboost:9.7.0.0
      > No cached version of com.chartboost:chartboost-sdk:9.7.0 available for offline mode.
      > No cached version of com.chartboost:chartboost-sdk:9.7.0 available for offline mode.
      > No cached version of com.chartboost:chartboost-sdk:9.7.0 available for offline mode.
      > No cached version of com.chartboost:chartboost-sdk:9.7.0 available for offline mode.
      > No cached version of com.chartboost:chartboost-sdk:9.7.0 available for offline mode.
      > No cached version of com.chartboost:chartboost-sdk:9.7.0 available for offline mode.

* Try:
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.3.3/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 7s
90 actionable tasks: 10 executed, 80 up-to-date
```

settings.gradle:
```
dependencyResolutionManagement {
    repositories {
        google()
        mavenCentral()

        maven {
            name = "IronSourceAdsRepo"
            url = "https://android-sdk.is.com/"
            content { it.includeGroup("com.ironsource.sdk") }
        }
        maven {
            name = "MintegralAdsRepo"
            url = "https://dl-maven-android.mintegral.com/repository/mbridge_android_sdk_oversea"
            content { it.includeGroup("com.mbridge.msdk.oversea") }
        }
        maven {
            name = "PangleAdsRepo"
            url = "https://artifact.bytedance.com/repository/pangle"
            content { it.includeGroup("com.pangle.global") }
        }
        maven {
            name = "SuperAwesomeAdsRepo"
            url = "https://aa-sdk.s3-eu-west-1.amazonaws.com/android_repo"
            content { it.includeGroup("tv.superawesome.sdk.publisher") }
        }
        maven {
            name = "ChartboostAdsRepo"
            url = "https://cboost.jfrog.io/artifactory/chartboost-ads/"
            content { it.includeGroup("com.chartboost") }
        }
    }
}
```

my_app/build.gradle:
```
dependencies {
    // Clever Ads Solutions (CAS)
    implementation("com.cleveradssolutions:cas-sdk:3.9.3")
    implementation("com.cleveradssolutions:cas-families:3.9.3")
}
```

What must I do to solve these 2 failures with ironsource and chartboost ?

**Comment by Str4tos** [comment]
Hi, thanks for reporting the issue.

The error message "No cached version of artifact available for offline mode" suggests that Gradle's offline mode might be enabled. Try toggle it to allow artifacts to cache properly. 
If offline mode is not active, check your internet connection.

Please let us know if this resolves the problem.

**Comment by julienpierron** [comment]
Thanks for your response.

Please note that when I sync Gradle, there no error. The errors appear when I try to Run the app.

When Gradle offline mode is enabled, I get this :
![image](https://github.com/user-attachments/assets/1f34ac8a-b380-4ad7-8820-606c6a8b072f)

And when it is disabled, I get that :
![image](https://github.com/user-attachments/assets/08e214e1-8360-42d7-b60c-5cb56d7a7ec0)

As you can see, there are 403 error codes.

And when I click on the last line `Gradle Sync issues`, there's this :
![image](https://github.com/user-attachments/assets/ae276ae1-a397-415b-839c-4748afa10cbc)

However, Gradle is already not using offline mode, and if I click on `Disable Gradle 'offline mode' and sync project`, Gradle becomes disabled automatically.

I have no internet connection issues, every other Gradle dependency that we have works properly. It's only with the newly added CAS dependencies that we are having this issue. If I revert back to my original code (before CAS implementation), there no Gradle issue.

**Comment by Str4tos** [comment]
Thank @julienpierron for the additional information.

This time, you’ve highlighted entirely different issues. Let’s go through them together. 

Note that you are receiving a 403 error from the SuperAwesome repository, which does not contain the required IronSource and Chartboost artifacts. These artifacts are located in other repositories. 

In the `settings.gradle` file you provided, it’s clear that the SuperAwesome repository is restricted to the artifact group `tv.superawesome.sdk.publisher`:
```groovy
url = "https://aa-sdk.s3-eu-west-1.amazonaws.com/android_repo"
content { it.includeGroup("tv.superawesome.sdk.publisher") }
```
It’s odd that Gradle is trying to find artifacts from a different group in this repository. 

Please check if there are any other locations where these repositories might be declared. 

I don’t see a `RepositoriesMode` definition in your `settings.gradle` file. You might want to add the following line to ensure that only repositories declared in the settings are considered:
```groovy
dependencyResolutionManagement {
    repositoriesMode = RepositoriesMode.PREFER_SETTINGS
    ...
}
```
Alternatively, you can specify `RepositoriesMode.FAIL_ON_PROJECT_REPOS` to trigger an error if there are unwanted repositories and help you locate their declarations.

Ensure that all necessary repositories are declared in the correct places and free from typos.

If you find that Gradle is accessing the correct repository (as defined in `settings.gradle`) but you still encounter artifact download errors, verify that the URL Gradle is trying to access opens without issues in your browser.

The repository might be inaccessible due to your provider’s restrictions. Unfortunately, we cannot guarantee the availability of all advertising SDK artifacts in our mediation. Using a VPN may help in downloading the required artifacts into Gradle’s cache.

Please keep me updated on your progress in resolving this issue.

**Comment by julienpierron** [comment]
Thank you very much. I think I've found a solution to my issue.

When I implemented CAS, I followed the setup from the wiki page, by placing the `repositories` in the `settings.gradle` file (`dependencyResolutionManagement > repositories`).
In our project however, our existing repositories are declared in files `build.gradle` and `my_app/build.gradle` (`buildscript > repositories`).

Moving the repositories needed for CAS from `settings.gradle` to our root `build.gradle` file seems solve the issue.

In our code however, it looks like CAS cannot be found
![image](https://github.com/user-attachments/assets/8144a5dc-7e7e-4ccc-9790-35aca8b88cde)

![image](https://github.com/user-attachments/assets/e5c607fa-17b7-4202-88d8-aa2f243668ff)

![image](https://github.com/user-attachments/assets/41d51cea-3d02-41d5-a7e2-d054577d122a)
